#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

##### Environment variable

# Editor
export EDITOR=nvim
export VISUAL=nvim
export MYVIMRC="~/.dotfiles/init.vim"


##### Aliases
alias cl=clear
alias vim=nvim
alias zshrc='vim ~/.zshrc'

# goto
alias gotopl='cd ~/Master/mcs-git/pl/'
alias gotoos-project='cd ~/Master/mcs-git/os/project/'
alias run-client='/home/snipy/Master/mcs-git/os/project/key-value-database/cmake-build-debug/src/client/client 127.0.0.1'
alias run-server='/home/snipy/Master/mcs-git/os/project/key-value-database/cmake-build-debug/src/server/server'
